### ISSUE TITLE
Commerce Email Template Not Found

### ISSUE THREAD

**Issue by mightyfineyall** [ostark/craft-async-queue#52]
I have a Commerce build that refused to send emails when this plugin was enabled. I'm using a custom template path (craft/src instead of craft/templates), and the emails would fail in the queue manager with an "HTML email template not found" error. As soon as I disabled the plugin, they all sent immediately without a hitch. We use Postmark to send SMTP mail. System emails sent just fine, but Commerce emails got stuck with this plugin enabled - one for two days, which is no bueno.

`2022-04-14 15:44:00 [-][-][-][error][craft\commerce\errors\EmailException] craft\commerce\errors\EmailException: Email template does not exist at “email/admin_order.html” which resulted in “email/admin_order.html” for email “Admin Order Notification”. Order: “f57631a”. in /srv/users/aeolus/apps/aeolus/craft/vendor/craftcms/commerce/src/queue/jobs/SendEmail.php:54

Stack trace:
#0 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2-queue/src/Queue.php(246): craft\commerce\queue\jobs\SendEmail->execute(Object(craft\queue\Queue))
#1 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('10608', 'O:35:"craft\\com...', '300', '1')
#2 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('10608', 'O:35:"craft\\com...', '300', '1', '305941')
#3 [internal function]: yii\queue\cli\Command->actionExec('10608', '300', '1', '305941')
#4 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('exec', Array)
#7 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('exec', Array)
#8 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#9 /srv/users/aeolus/apps/aeolus/craft/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('queue/exec', Array)
#10 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/exec', Array)
#11 /srv/users/aeolus/apps/aeolus/craft/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#12 /srv/users/aeolus/apps/aeolus/craft/craft(27): yii\base\Application->run()
#13 {main}`

**Comment by ostark** [comment]
I can't imagine it is related to the plugin.
Try 
```
php craft queue/listen -v
```
